// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file src/proto/calculator.proto (package calculator, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Operands, Result } from "./calculator_pb"; // 修改导入路径为 TypeScript 文件
import { MethodKind } from "@bufbuild/protobuf";

/**
 * 定义计算器服务
 *
 * @generated from service calculator.Calculator
 */
export const Calculator = {
  typeName: "calculator.Calculator",
  methods: {
    /**
     * @generated from rpc calculator.Calculator.Add
     */
    add: {
      name: "Add",
      I: Operands,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc calculator.Calculator.Subtract
     */
    subtract: {
      name: "Subtract",
      I: Operands,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc calculator.Calculator.Multiply
     */
    multiply: {
      name: "Multiply",
      I: Operands,
      O: Result,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc calculator.Calculator.Divide
     */
    divide: {
      name: "Divide",
      I: Operands,
      O: Result,
      kind: MethodKind.Unary,
    },
  }
} as const;

